S3 adapter is exist
syngenta-digital/dta-python pull request #63
Opened 2021-08-17 18:06 UTC by abdullah-syngenta

2021-08-18 12:33 UTC, paulcruse-syn requested changes
LGTM, just one small change.

2021-08-18 12:33 UTC, paulcruse-syn commented on syngenta_digital_dta/s3/adapter.py
> +    def is_exist(self, s3_path):
```suggestion
    def object_exist(self, **kwargs):
```

Think is a more accurate method name. The other method could apply to any resource within S3 instead of what you are implying, the object. 

Also to stay consistent with the other methods we should use kwargs. This way it's easy to add more non, breaking features in the future. 

I think your tests can remain the same since python 3 will interpret positional arguments with the same variable name as a keyword argument. Just need to change the inner logic of the method to reference the kwarg.

2021-08-18 13:53 UTC, abdullah-syngenta commented on syngenta_digital_dta/s3/adapter.py
> +    def is_exist(self, s3_path):
Done .. I just wonder why tests are failing .. also unauthorized status when I try to access pipeline

2021-08-20 18:20 UTC, paulcruse-syn requested changes
See if the suggestion works, if not we can do it your way.

2021-08-20 18:20 UTC, paulcruse-syn commented on syngenta_digital_dta/s3/adapter.py
>          if 'Contents' in results:
Instead of doing this loop, have you seen this response from stack overflow:
https://stackoverflow.com/questions/33842944/check-if-a-key-exists-in-a-bucket-in-s3-using-boto3

There should be a `self.resource` you can use to access the same logic:

```python
try:
    self.resource.Object(self.bucket, kwargs['s3_path']).load()
except botocore.exceptions.ClientError as error:
    if error.response['Error']['Code'] == "404":
        # The object does not exist.
    else:
        # Something else has gone wrong.
        raise
else:
   # object does exist
```

2021-08-24 14:24 UTC, abdullah-syngenta commented on syngenta_digital_dta/s3/adapter.py
>          if 'Contents' in results:
Looks a better solution .. i have applied it, please check

2021-08-24 15:17 UTC, paulcruse-syn approved these changes

2021-08-24 15:23 UTC, paulcruse-syn commented
@abdullah-syngenta you're branch is failing due to linting.

2021-08-24 16:57 UTC, paulcruse-syn approved these changes

2021-08-24 19:15 UTC, merged